# Generated by Django 4.0.3 on 2023-01-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_booking', '0002_alter_court_court_name'),
        ('court_booking', '0003_remove_profile_id_alter_profile_user'),
    ]

    operations = [
    ]
